<?php

namespace WCS\LyonGameBundle\Repository;

/**
 * StopOverRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class StopOverRepository extends \Doctrine\ORM\EntityRepository
{
}
