<?php

namespace WCS\LyonGameBundle\Repository;


use WCS\LyonGameBundle\Entity\Trip;
use Doctrine\ORM\EntityRepository;
use Doctrine\ORM\Tools\Pagination\Paginator;

/**
 * TripRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TripRepository extends EntityRepository
{
	public function getTripUnesco()
	{
		$query = $this->createQueryBuilder('t')
			->innerJoin("t.tripEnglishs", "te")
			->innerJoin("t.stopOvers", "st")
			->where("t.slug = 'unesco'")
			->getQuery();
		return $query->getResult();
	}

	public function getTripPokemonGo () {
		$query = $this->createQueryBuilder('t')
			->where("t.slug = 'pokemon-go'")
			->getQuery();
		return $query->getResult();
	}
}
