<?php

namespace WCS\LyonGameBundle\Repository;

/**
 * TripRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TripRepository extends \Doctrine\ORM\EntityRepository
{
    public function getTripUnesco () {
        $query = $this->createQueryBuilder('t')
            ->where("p.slug = 'unesco'")
        ;
        return $query->getResult();
    }
}
