<?php

namespace WCS\LyonGameBundle\Repository;

/**
 * TripEnglishRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TripEnglishRepository extends \Doctrine\ORM\EntityRepository
{
}
